# Generated by Django 2.2 on 2019-09-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='Female', max_length=10)),
                ('ContactNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
