# Generated by Django 2.2 on 2019-09-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyformapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='Age',
            field=models.IntegerField(default=0),
        ),
    ]
